# Generated by Django 4.0.6 on 2022-07-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomreservation',
            name='meeting_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 13, 27, 56, 659517)),
        ),
        migrations.AlterField(
            model_name='meetingroomreservation',
            name='meeting_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 13, 27, 56, 659517)),
        ),
    ]
