# Generated by Django 4.0.6 on 2022-07-21 10:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_meetingroomreservation_meeting_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meetingroomreservation',
            name='meeting_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meetingroomreservation',
            name='meeting_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
