# Generated by Django 4.0.6 on 2022-07-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_meetingroom_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroomreservation',
            name='meeting_room',
        ),
        migrations.AddField(
            model_name='meetingroomreservation',
            name='meeting_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_reservation', to='app.meetingroom'),
            preserve_default=False,
        ),
    ]
